services:
    cleverage_rest_process.task.request:
        class: CleverAge\RestProcessBundle\Task\RequestTask
        public: false
        shared: false
        arguments:
            - '@logger'
            - '@cleverage_rest_process.registry.client'
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }
    CleverAge\RestProcessBundle\Task\RequestTask:
        alias: cleverage_rest_process.task.request
        public: true
